### ISSUE TITLE
Can't get it to work no modules available

### ISSUE THREAD

**Issue by Dragoy** [qunat/EasyNuitka#3]
I get the following error, on startup, what could be the problem?

```
PS C:\Program Files\Nuitka-2.3.1> python -m EasyNuitka
Traceback (most recent call last):
  File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\site-packages\EasyNuitka\__main__.py", line 14, in <module>
    import mainui
ModuleNotFoundError: No module named 'mainui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\site-packages\EasyNuitka\__main__.py", line 16, in <module>
    from . import mainui
  File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\site-packages\EasyNuitka\mainui.py", line 12, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

**Comment by qunat** [comment]
楼建迪
***@***.***







                       
原始邮件
                       
                     

发件人："Dragoy"< ***@***.*** &gt;;

发件时间：2024/6/10 6:04

收件人："qunat/EasyNuitka"< ***@***.*** &gt;;

抄送人："Subscribed"< ***@***.*** &gt;;

主题：[qunat/EasyNuitka] Can't get it to work no modules available (Issue#3)




 
I get the following error, on startup, what could be the problem?
 PS C:\Program Files\Nuitka-2.3.1&gt; python -m EasyNuitka Traceback (most recent call last):   File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\site-packages\EasyNuitka\__main__.py", line 14, in <module&gt;     import mainui ModuleNotFoundError: No module named 'mainui' During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main     return _run_code(code, main_globals, None,   File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code     exec(code, run_globals)   File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\site-packages\EasyNuitka\__main__.py", line 16, in <module&gt;     from . import mainui   File "C:\Users\Dragoy\AppData\Local\Programs\Python\Python310\lib\site-packages\EasyNuitka\mainui.py", line 12, in <module&gt;     import resource ModuleNotFoundError: No module named 'resource'
